Handle ConnectionError without a response
E.g.:

```
ConnectionError: HTTPSConnectionPool(host='api.soundcloud.com',
port=443): Max retries exceeded with url:
/me.json?client_id=XXX (Caused by
NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection
object at 0x7f4356c37550>: Failed to establish a new connection: [Errno
-2] Name or service not known',))
```